apiVersion: v1
kind: Namespace
metadata:
  name: fiapx
---
# ConfigMap com as URLs dos serviços (injetado em appsettings.Production.json via nginx)
# O Blazor WASM lê o appsettings.json do wwwroot — para K8s, montamos um ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: fiapx
data:
  appsettings.Production.json: |
    {
      "Services": {
        "Auth":         "http://auth-service/",
        "Upload":       "http://upload-service/",
        "Processor":    "http://processor-service/",
        "Notification": "http://notification-service/"
      }
    }
